// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewsNode.Services.GroupChats.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NewsNode.Services.GroupChats.Database.Migrations
{
    [DbContext(typeof(GroupChatsDbContext))]
    [Migration("20250212231736_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("group_chats")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NewsNode.Services.GroupChats.GroupChats.GroupChat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("GroupChats", "group_chats");
                });

            modelBuilder.Entity("NewsNode.Services.GroupChats.GroupChats.GroupUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupChatId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "GroupChatId")
                        .IsUnique();

                    b.ToTable("GroupUsers", "group_chats");
                });

            modelBuilder.Entity("NewsNode.Services.GroupChats.GroupChats.GroupChat", b =>
                {
                    b.OwnsMany("NewsNode.Shared.Abstractions.Kernel.ValueObjects.Hashtag", "Hashtags", b1 =>
                        {
                            b1.Property<Guid>("GroupChatId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Hashtag");

                            b1.HasKey("GroupChatId", "Id");

                            b1.ToTable("Hashtag", "group_chats");

                            b1.WithOwner()
                                .HasForeignKey("GroupChatId");
                        });

                    b.Navigation("Hashtags");
                });
#pragma warning restore 612, 618
        }
    }
}
