version: '3.9'

networks:
  NewsNode.Network:
    name: NewsNode.Network

services:
  newsnode.postgres:
    image: postgres:latest
    container_name: NewsNode.Postgres
    hostname: NewsNode.Postgres
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5433:5433"
    volumes:
      - ./.container/newsnode.postgres:/var/lib/postgresql
      - ./.container/newsnode.postgres:/var/log/postgresql
    command: -p 5433
    networks:
      - NewsNode.Network

  newsnode.redis:
    image: redis:latest
    container_name: newsnode.Redis
    hostname: newsnode.Redis
    ports:
      - "6379:6379"
    volumes:
      - ./.container/redis:/data
      - ./.container/redis:/var/log/redis

volumes:
  postgres:
    driver: local