// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewsNode.Modules.Socials.Infrastructure.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NewsNode.Modules.Socials.Infrastructure.Database.Migrations
{
    [DbContext(typeof(SocialsDbContext))]
    [Migration("20250103172409_AddedDislikes")]
    partial class AddedDislikes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("socials")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NewsNode.Modules.Socials.Domain.Post.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Bookmarks")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("Likes")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PostId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Reposts")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Comments", "socials");
                });

            modelBuilder.Entity("NewsNode.Modules.Socials.Domain.Post.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Bookmarks")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("Likes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Reposts")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Posts", "socials");
                });

            modelBuilder.Entity("NewsNode.Modules.Socials.Domain.UserProfile.PostAction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Post_actions", "socials");
                });

            modelBuilder.Entity("NewsNode.Modules.Socials.Domain.UserProfile.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User_profiles", "socials");
                });

            modelBuilder.Entity("NewsNode.Modules.Socials.Domain.UserProfile.UserProfileFollow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("User_profile_follows", "socials");
                });

            modelBuilder.Entity("NewsNode.Modules.Socials.Domain.UserProfile.UserProfileStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("User_profile_statuses", "socials");
                });

            modelBuilder.Entity("NewsNode.Modules.Socials.Domain.Post.Comment", b =>
                {
                    b.HasOne("NewsNode.Modules.Socials.Domain.Post.Post", null)
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NewsNode.Modules.Socials.Domain.Post.Post", b =>
                {
                    b.OwnsMany("NewsNode.Shared.Abstractions.Kernel.ValueObjects.Hashtag", "Hashtags", b1 =>
                        {
                            b1.Property<Guid>("PostId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Hashtag");

                            b1.HasKey("PostId", "Id");

                            b1.ToTable("Hashtag", "socials");

                            b1.WithOwner()
                                .HasForeignKey("PostId");
                        });

                    b.Navigation("Hashtags");
                });

            modelBuilder.Entity("NewsNode.Modules.Socials.Domain.UserProfile.PostAction", b =>
                {
                    b.HasOne("NewsNode.Modules.Socials.Domain.UserProfile.UserProfile", null)
                        .WithMany("PostActions")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NewsNode.Modules.Socials.Domain.UserProfile.UserProfileFollow", b =>
                {
                    b.HasOne("NewsNode.Modules.Socials.Domain.UserProfile.UserProfile", null)
                        .WithMany("ProfileFollows")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NewsNode.Modules.Socials.Domain.UserProfile.UserProfileStatus", b =>
                {
                    b.HasOne("NewsNode.Modules.Socials.Domain.UserProfile.UserProfile", null)
                        .WithMany("ProfileStatuses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NewsNode.Modules.Socials.Domain.Post.Post", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("NewsNode.Modules.Socials.Domain.UserProfile.UserProfile", b =>
                {
                    b.Navigation("PostActions");

                    b.Navigation("ProfileFollows");

                    b.Navigation("ProfileStatuses");
                });
#pragma warning restore 612, 618
        }
    }
}
