// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewsNode.Services.Recommendations.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NewsNode.Services.Recommendations.Database.Migrations
{
    [DbContext(typeof(RecommendationsDbContext))]
    [Migration("20250109182426_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("recommendations")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NewsNode.Services.Recommendations.Recommendations.Recommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Hashtag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastInteraction")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Recommendations", "recommendations");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("NewsNode.Services.Recommendations.Recommendations.ActionRecommendation", b =>
                {
                    b.HasBaseType("NewsNode.Services.Recommendations.Recommendations.Recommendation");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.ToTable("ActionRecommendations", "recommendations");
                });

            modelBuilder.Entity("NewsNode.Services.Recommendations.Recommendations.CountryRecommendation", b =>
                {
                    b.HasBaseType("NewsNode.Services.Recommendations.Recommendations.Recommendation");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.ToTable("CountryRecommendations", "recommendations");
                });

            modelBuilder.Entity("NewsNode.Services.Recommendations.Recommendations.ActionRecommendation", b =>
                {
                    b.HasOne("NewsNode.Services.Recommendations.Recommendations.Recommendation", null)
                        .WithOne()
                        .HasForeignKey("NewsNode.Services.Recommendations.Recommendations.ActionRecommendation", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NewsNode.Services.Recommendations.Recommendations.CountryRecommendation", b =>
                {
                    b.HasOne("NewsNode.Services.Recommendations.Recommendations.Recommendation", null)
                        .WithOne()
                        .HasForeignKey("NewsNode.Services.Recommendations.Recommendations.CountryRecommendation", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
