<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>f8bccf8f-ee16-4ab8-8321-5bb40800df85</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Build" Version="17.12.6"/>
        <PackageReference Include="Microsoft.Build.Framework" Version="17.12.6"/>

        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.0"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Modules\Socials\NewsNode.Modules.Socials.Api\NewsNode.Modules.Socials.Api.csproj" />
        <ProjectReference Include="..\..\Modules\Social\NewsNode.Modules.Social.Api\NewsNode.Modules.Social.Api.csproj" />
        <ProjectReference Include="..\..\Modules\Users\NewsNode.Modules.Users.Api\NewsNode.Modules.Users.Api.csproj"/>
        <ProjectReference Include="..\..\Shared\NewsNode.Shared.Infrastructure\NewsNode.Shared.Infrastructure.csproj"/>
    </ItemGroup>

</Project>