<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>NewsNode.Services.GroupChats</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Shared\NewsNode.Shared.Abstractions\NewsNode.Shared.Abstractions.csproj" />
      <ProjectReference Include="..\..\Shared\NewsNode.Shared.Infrastructure\NewsNode.Shared.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.1"/>
    </ItemGroup>

</Project>
